version: '3.8'

# Test environment overrides
services:
  postgres:
    environment:
      POSTGRES_DB: financial_analysis_test
    volumes:
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  api:
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/financial_analysis_test
      JWT_SECRET_KEY: test-secret-key-for-ci
      DEBUG: "true"
      LOG_LEVEL: DEBUG
    command: |
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        alembic upgrade head &&
        uvicorn src.api.main:app --host 0.0.0.0 --port 8000
      "

  # Test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financial_test_runner
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/financial_analysis_test
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: test-secret-key-for-ci
      DEBUG: "true"
      LOG_LEVEL: DEBUG
    command: |
      sh -c "
        echo 'Waiting for services...' &&
        sleep 15 &&
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
      "
    depends_on:
      - postgres
      - redis
    networks:
      - financial_network
    volumes:
      - .:/app
      - /app/.venv