apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: recommendation-system
  labels:
    app: graphql-recommendation-api
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: graphql-recommendation-api
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: api-headless
  namespace: recommendation-system
  labels:
    app: graphql-recommendation-api
    component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: graphql-recommendation-api
    component: api