apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: graphql-recommendation-api

namespace: recommendation-system

resources:
  # Namespace
  - namespace.yaml
  
  # API components
  - api/configmap.yaml
  - api/secret.yaml
  - api/rbac.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  
  # Database
  - database/postgres.yaml
  
  # Cache and Vector DB
  - cache/redis-cluster.yaml
  - cache/qdrant.yaml
  
  # Monitoring
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - monitoring/jaeger.yaml
  
  # Ingress
  - ingress/ingress.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: graphql-recommendation-api
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/part-of: recommendation-system

# Image transformations
images:
  - name: graphql-recommendation-api
    newTag: latest

# ConfigMap and Secret generators
configMapGenerator:
  - name: deployment-config
    literals:
      - deployment.timestamp=2024-01-01T00:00:00Z

# Patches for different environments
patchesStrategicMerge: []

# Patches using JSON 6902
patches: []