apiVersion: v1
kind: Namespace
metadata:
  name: recommendation-system
  labels:
    name: recommendation-system
    app.kubernetes.io/name: graphql-recommendation-api
    app.kubernetes.io/version: "1.0.0"