apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rust-web-server-metrics
  namespace: rust-web-server
  labels:
    app: rust-web-server
spec:
  selector:
    matchLabels:
      app: rust-web-server
  endpoints:
  - port: http
    path: /api/metrics
    interval: 30s
    scrapeTimeout: 10s