[features]
resolution = true
skip-lint = false

[programs.localnet]
defi_lending_protocol = "DLendpNGzTTDdRsQHBJyYgQV9qR8JwKyFfvKSzWE8hT"
governance_token = "GovToknAbCdEfGhIjKlMnOpQrStUvWxYz123456789"

[programs.devnet]
defi_lending_protocol = "DLendpNGzTTDdRsQHBJyYgQV9qR8JwKyFfvKSzWE8hT"
governance_token = "GovToknAbCdEfGhIjKlMnOpQrStUvWxYz123456789"

[programs.mainnet]
defi_lending_protocol = "DLendpNGzTTDdRsQHBJyYgQV9qR8JwKyFfvKSzWE8hT"
governance_token = "GovToknAbCdEfGhIjKlMnOpQrStUvWxYz123456789"

[registry]
url = "https://api.anchor.so"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/defi-lending-protocol",
    "programs/governance-token"
]

[toolchain]