apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: recommendation-system
  labels:
    app: jaeger
    component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: all-in-one
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          protocol: UDP
          name: zk-compact-trft
        - containerPort: 6831
          protocol: UDP
          name: jg-compact-trft
        - containerPort: 6832
          protocol: UDP
          name: jg-binary-trft
        - containerPort: 5778
          protocol: TCP
          name: config-rest
        - containerPort: 16686
          protocol: TCP
          name: query
        - containerPort: 14268
          protocol: TCP
          name: c-tchan-trft
        - containerPort: 14250
          protocol: TCP
          name: grpc
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: recommendation-system
  labels:
    app: jaeger
    component: query
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
    name: query
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: recommendation-system
  labels:
    app: jaeger
    component: collector
spec:
  type: ClusterIP
  ports:
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: c-tchan-trft
  - port: 14250
    targetPort: 14250
    protocol: TCP
    name: grpc
  selector:
    app: jaeger
    component: all-in-one
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: recommendation-system
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: zk-compact-trft
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jg-compact-trft
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: jg-binary-trft
  - port: 5778
    targetPort: 5778
    protocol: TCP
    name: config-rest
  selector:
    app: jaeger
    component: all-in-one